# Generated by Django 4.2.7 on 2023-11-28 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='historical_performance_mode',
            new_name='HistoricalPerformance',
        ),
    ]
