# Generated by Django 4.2.7 on 2023-11-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0002_rename_historical_performance_mode_historicalperformance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vendor',
            unique_together={('vendor_code', 'id')},
        ),
    ]
