# Generated by Django 4.2.7 on 2023-11-29 06:43

from django.db import migrations
import vendor_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_alter_vendor_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=vendor_app.models.UniqueVendorCodeField(max_length=255, unique=True),
        ),
    ]
