# Generated by Django 4.2.7 on 2023-11-29 08:57

from django.db import migrations
import vendor_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0006_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=vendor_app.models.UniqueVendorCodeField(max_length=255, unique=True),
        ),
    ]
